del /q /f /s ..\scriptPackages\*
rmdir /q /s ..\scriptPackages

mkdir ..\scriptPackages
mkdir ..\scriptPackages\prefs
mkdir ..\scriptPackages\prefs\icons
mkdir ..\scriptPackages\scripts
mkdir ..\scriptPackages\scripts\filesystem
mkdir ..\scriptPackages\scripts\CST
mkdir ..\scriptPackages\scripts\rigger
mkdir ..\scriptPackages\scripts\zz_scripts

copy _topDistro\*.* ..\scriptPackages
copy prefs\icons\*.* ..\scriptPackages\prefs\icons


copy *.py                                                 ..\scriptPackages\scripts\
copy filesystem\*.py                                      ..\scriptPackages\scripts\filesystem\
copy dagMenuProc_v2009.mel                                ..\scriptPackages\scripts\
copy gatherFileDeps.mel                                   ..\scriptPackages\scripts\
copy listProcs.mel                                        ..\scriptPackages\scripts\
copy p4.mel                                               ..\scriptPackages\scripts\
copy p4menu.mel                                           ..\scriptPackages\scripts\
copy procDef.mel                                          ..\scriptPackages\scripts\
copy remEds.mel                                           ..\scriptPackages\scripts\
copy src.mel                                              ..\scriptPackages\scripts\
copy userSetup.mel                                        ..\scriptPackages\scripts\
copy zooAddCameraMask.mel                                 ..\scriptPackages\scripts\
copy zooAlign.mel                                         ..\scriptPackages\scripts\
copy zooAnimFile.mel                                      ..\scriptPackages\scripts\
copy zooAnimStore.mel                                     ..\scriptPackages\scripts\
copy zooAnimStoreDependencies.mel                         ..\scriptPackages\scripts\
copy zooAnimStoreUtils.mel                                ..\scriptPackages\scripts\
copy zooArrays_float.mel                                  ..\scriptPackages\scripts\
copy zooArrays_int.mel                                    ..\scriptPackages\scripts\
copy zooArrays_str.mel                                    ..\scriptPackages\scripts\
copy zooAssets.mel                                        ..\scriptPackages\scripts\
copy zooAssetsDependencies.mel                            ..\scriptPackages\scripts\
copy zooAssetsHelp.zooHelp                                ..\scriptPackages\scripts\
copy zooAssetsTechnical.zooHelp                           ..\scriptPackages\scripts\
copy zooAssetsTips.txt                                    ..\scriptPackages\scripts\
copy zooAssetsUtils.mel                                   ..\scriptPackages\scripts\
copy zooAssetsWin.mel                                     ..\scriptPackages\scripts\
copy zooAttrScroller.mel                                  ..\scriptPackages\scripts\
copy zooAttrUtils.mel                                     ..\scriptPackages\scripts\
copy zooAutoSave.mel                                      ..\scriptPackages\scripts\
copy zooBGBlaster.mel                                     ..\scriptPackages\scripts\
copy zooBGBlasterDependencies.mel                         ..\scriptPackages\scripts\
copy zooBGBlasterUtils.mel                                ..\scriptPackages\scripts\
copy zooBlendToSdk.mel                                    ..\scriptPackages\scripts\
copy zooBodgeK.mel                                        ..\scriptPackages\scripts\
copy zooBodgeKDependencies.mel                            ..\scriptPackages\scripts\
copy zooBodgeK_help.zooHelp                               ..\scriptPackages\scripts\
copy zooBoltOnIK.mel                                      ..\scriptPackages\scripts\
copy zooBoltOnIKWin.mel                                   ..\scriptPackages\scripts\
copy zooBounds.mel                                        ..\scriptPackages\scripts\
copy zooBrandTools.mel                                    ..\scriptPackages\scripts\
copy zooBreakTime.mel                                     ..\scriptPackages\scripts\
copy zooBuildControl.mel                                  ..\scriptPackages\scripts\
copy zooCam.mel                                           ..\scriptPackages\scripts\
copy zooChangeRoo.mel                                     ..\scriptPackages\scripts\
copy zooChangeSpace.mel                                   ..\scriptPackages\scripts\
copy zooCurveLight.mel                                    ..\scriptPackages\scripts\
copy zooDates.mel                                         ..\scriptPackages\scripts\
copy zooDeleteStaticChannels.mel                          ..\scriptPackages\scripts\
copy zooDynChain.mel                                      ..\scriptPackages\scripts\
copy zooEazelUtils.mel                                    ..\scriptPackages\scripts\
copy zooFitTimeline.mel                                   ..\scriptPackages\scripts\
copy zooFlags.mel                                         ..\scriptPackages\scripts\
copy zooGetLookat.mel                                     ..\scriptPackages\scripts\
copy zooGraphFilter.mel                                   ..\scriptPackages\scripts\
copy zooGraphFilterUtils.mel                              ..\scriptPackages\scripts\
copy zooGreaseMonkey.mel                                  ..\scriptPackages\scripts\
copy zooGreaseMonkeyDependencies.mel                      ..\scriptPackages\scripts\
copy zooGreaseMonkeyTips.txt                              ..\scriptPackages\scripts\
copy zooGreaseMonkeyUtils.mel                             ..\scriptPackages\scripts\
copy zooGreaseMonkey_help.zooHelp                         ..\scriptPackages\scripts\
copy zooHeavy.mel                                         ..\scriptPackages\scripts\
copy zooHeavyDependencies.mel                             ..\scriptPackages\scripts\
copy zooHeavyMenu.mel                                     ..\scriptPackages\scripts\
copy zooHeavyTips.txt                                     ..\scriptPackages\scripts\
copy zooHeavyUtils.mel                                    ..\scriptPackages\scripts\
copy zooHelp.mel                                          ..\scriptPackages\scripts\
copy zooHotkeyer.mel                                      ..\scriptPackages\scripts\
copy zooHUDCtrl.mel                                       ..\scriptPackages\scripts\
copy zooInterestCalc.mel                                  ..\scriptPackages\scripts\
copy zooKeyCommands.mel                                   ..\scriptPackages\scripts\
copy zooKeyCommandsWin.mel                                ..\scriptPackages\scripts\
copy zooKeyCommands_help.zooHelp                          ..\scriptPackages\scripts\
copy zooKeymaster.mel                                     ..\scriptPackages\scripts\
copy zooKeymasterDependencies.mel                         ..\scriptPackages\scripts\
copy zooKeymasterMenu.mel                                 ..\scriptPackages\scripts\
copy zooKeymasterWin.mel                                  ..\scriptPackages\scripts\
copy zooKeymaster_help.zooHelp                            ..\scriptPackages\scripts\
copy zooKeyUtils.mel                                      ..\scriptPackages\scripts\
copy zooLineOfAction.mel                                  ..\scriptPackages\scripts\
copy zooLockFile.mel                                      ..\scriptPackages\scripts\
copy zooMatchNames.mel                                    ..\scriptPackages\scripts\
copy zooMirror.mel                                        ..\scriptPackages\scripts\
copy zooMirrorSelection.mel                               ..\scriptPackages\scripts\
copy zooMirrorUtils.mel                                   ..\scriptPackages\scripts\
copy zooNameSpacey.mel                                    ..\scriptPackages\scripts\
copy zooNameSpaceyDependencies.mel                        ..\scriptPackages\scripts\
copy zooNameSpaceyUtils.mel                               ..\scriptPackages\scripts\
copy zooNameSpacey_help.zooHelp                           ..\scriptPackages\scripts\
copy zooObjMenu.mel                                       ..\scriptPackages\scripts\
copy zooObjMenuUtils.mel                                  ..\scriptPackages\scripts\
copy zooObjMenu_help.zooHelp                              ..\scriptPackages\scripts\
copy zooPack.mel                                          ..\scriptPackages\scripts\
copy zooPanelCycler.mel                                   ..\scriptPackages\scripts\
copy zooParentToChild.mel                                 ..\scriptPackages\scripts\
copy zooPickwalk.mel                                      ..\scriptPackages\scripts\
copy zooPickwalkAuthor.mel                                ..\scriptPackages\scripts\
copy zooPickwalkDependencies.mel                          ..\scriptPackages\scripts\
copy zooPickwalkPresets.mel                               ..\scriptPackages\scripts\
copy zooPickwalkTips.txt                                  ..\scriptPackages\scripts\
copy zooPickwalk_help.zooHelp                             ..\scriptPackages\scripts\
copy zooPollster.mel                                      ..\scriptPackages\scripts\
copy zooPollsterMenu.mel                                  ..\scriptPackages\scripts\
copy zooPosesToSliders.mel                                ..\scriptPackages\scripts\
copy zooPresetManager.mel                                 ..\scriptPackages\scripts\
copy zooReblender.mel                                     ..\scriptPackages\scripts\
copy zooRegister.mel                                      ..\scriptPackages\scripts\
copy zooRegisterWin.mel                                   ..\scriptPackages\scripts\
copy zooRemind.mel                                        ..\scriptPackages\scripts\
copy zooRenamer.mel                                       ..\scriptPackages\scripts\
copy zooRenamerUtils.mel                                  ..\scriptPackages\scripts\
copy zooRenamer_help.zooHelp                              ..\scriptPackages\scripts\
copy zooReorderAttribs.mel                                ..\scriptPackages\scripts\
copy zooReorderAttrs.mel                                  ..\scriptPackages\scripts\
copy zooReplaceShape.mel                                  ..\scriptPackages\scripts\
copy zooResetAttrs.mel                                    ..\scriptPackages\scripts\
copy zooResource.mel                                      ..\scriptPackages\scripts\
copy zooSelecto.mel                                       ..\scriptPackages\scripts\
copy zooSelectoDependencies.mel                           ..\scriptPackages\scripts\
copy zooSelectoMenu.mel                                   ..\scriptPackages\scripts\
copy zooSelectoPresets.mel                                ..\scriptPackages\scripts\
copy zooSelectoTips.txt                                   ..\scriptPackages\scripts\
copy zooSelectoUtils.mel                                  ..\scriptPackages\scripts\
copy zooSendMail.mel                                      ..\scriptPackages\scripts\
copy zooSetkey.mel                                        ..\scriptPackages\scripts\
copy zooSetLookat.mel                                     ..\scriptPackages\scripts\
copy zooSetMenu.mel                                       ..\scriptPackages\scripts\
copy zooSetMenu_help.zooHelp                              ..\scriptPackages\scripts\
copy zooShaders.mel                                       ..\scriptPackages\scripts\
copy zooShelveIt.mel                                      ..\scriptPackages\scripts\
copy zooShots.mel                                         ..\scriptPackages\scripts\
copy zooShotsDependencies.mel                             ..\scriptPackages\scripts\
copy zooShotsHelp.zooHelp                                 ..\scriptPackages\scripts\
copy zooShotsUtils.mel                                    ..\scriptPackages\scripts\
copy zooSketchy.mel                                       ..\scriptPackages\scripts\
copy zooSketchyDependencies.mel                           ..\scriptPackages\scripts\
copy zooSketchyUtils.mel                                  ..\scriptPackages\scripts\
copy zooSortToHeirarchy.mel                               ..\scriptPackages\scripts\
copy zooSpaceSwitching.mel                                ..\scriptPackages\scripts\
copy zooStickToCurve.mel                                  ..\scriptPackages\scripts\
copy zooStriderUtils.mel                                  ..\scriptPackages\scripts\
copy zooStrMatrix.mel                                     ..\scriptPackages\scripts\
copy zooStrUtils.mel                                      ..\scriptPackages\scripts\
copy zooSurgeon.mel                                       ..\scriptPackages\scripts\
copy zooSurgeonDependencies.mel                           ..\scriptPackages\scripts\
copy zooSurgeonUtils.mel                                  ..\scriptPackages\scripts\
copy zooTangentWks.mel                                    ..\scriptPackages\scripts\
copy zooTangentWksUtils.mel                               ..\scriptPackages\scripts\
copy zooTips.mel                                          ..\scriptPackages\scripts\
copy zooToggle.mel                                        ..\scriptPackages\scripts\
copy zooToggleUI.mel                                      ..\scriptPackages\scripts\
copy zooToolBox.mel                                       ..\scriptPackages\scripts\
copy zooToolBoxDependencies.mel                           ..\scriptPackages\scripts\
copy zooToolBoxTips.txt                                   ..\scriptPackages\scripts\
copy zooToolBox_help.zooHelp                              ..\scriptPackages\scripts\
copy zooToolBox_toolList.zooHelp                          ..\scriptPackages\scripts\
copy zooTriggerator.mel                                   ..\scriptPackages\scripts\
copy zooTriggeratorTips.txt                               ..\scriptPackages\scripts\
copy zooTriggeratorUtils.mel                              ..\scriptPackages\scripts\
copy zooTriggered.mel                                     ..\scriptPackages\scripts\
copy zooTriggeredDependencies.mel                         ..\scriptPackages\scripts\
copy zooTriggeredHelp.zooHelp                             ..\scriptPackages\scripts\
copy zooTriggeredPresets.mel                              ..\scriptPackages\scripts\
copy zooTriggeredTech.zooHelp                             ..\scriptPackages\scripts\
copy zooTriggeredUtils.mel                                ..\scriptPackages\scripts\
copy zooTriggeredWin.mel                                  ..\scriptPackages\scripts\
copy zooUpdates.mel                                       ..\scriptPackages\scripts\
copy zooUtils.mel                                         ..\scriptPackages\scripts\
copy zooVectors.mel                                       ..\scriptPackages\scripts\
copy zooVisMan.mel                                        ..\scriptPackages\scripts\
copy zooVisManDependencies.mel                            ..\scriptPackages\scripts\
copy zooVisManUtils.mel                                   ..\scriptPackages\scripts\
copy zooWeightSave.mel                                    ..\scriptPackages\scripts\
copy zooWeightSaveDependencies.mel                        ..\scriptPackages\scripts\
copy zooWeightSave_help.zooHelp                           ..\scriptPackages\scripts\
copy zooXferAnim.mel                                      ..\scriptPackages\scripts\
copy zooXferAnimDependencies.mel                          ..\scriptPackages\scripts\
copy zooXferAnimTips.txt                                  ..\scriptPackages\scripts\
copy zooXferAnimUtils.mel                                 ..\scriptPackages\scripts\
copy zooXferAnim_about.zooHelp                            ..\scriptPackages\scripts\
copy zooXferAnim_scripting.zooHelp                        ..\scriptPackages\scripts\
copy zooXferWeights.mel                                   ..\scriptPackages\scripts\
copy zooZipScript.mel                                     ..\scriptPackages\scripts\
copy CST\control.arrow.shape                              ..\scriptPackages\scripts\CST\
copy CST\control.band.shape                               ..\scriptPackages\scripts\CST\
copy CST\control.cone.shape                               ..\scriptPackages\scripts\CST\
copy CST\control.cube.shape                               ..\scriptPackages\scripts\CST\
copy CST\control.cylinder.shape                           ..\scriptPackages\scripts\CST\
copy CST\control.eye.shape                                ..\scriptPackages\scripts\CST\
copy CST\control.face.shape                               ..\scriptPackages\scripts\CST\
copy CST\control.hand.shape                               ..\scriptPackages\scripts\CST\
copy CST\control.hex.shape                                ..\scriptPackages\scripts\CST\
copy CST\control.locator.shape                            ..\scriptPackages\scripts\CST\
copy CST\control.pin.shape                                ..\scriptPackages\scripts\CST\
copy CST\control.pointer.shape                            ..\scriptPackages\scripts\CST\
copy CST\control.ring.shape                               ..\scriptPackages\scripts\CST\
copy CST\control.sphere.shape                             ..\scriptPackages\scripts\CST\
copy CST\control.starcircle.shape                         ..\scriptPackages\scripts\CST\
copy CST\control.target.shape                             ..\scriptPackages\scripts\CST\
copy CST\control.textall.shape                            ..\scriptPackages\scripts\CST\
copy CST\zooCST.mel                                       ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildIKFK.mel                              ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildIKFK_altTwist.mel                     ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildMPath.mel                             ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimArm.mel                           ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimBasicSpine.mel                    ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimEyes.mel                          ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimFinger.mel                        ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimFKSpine.mel                       ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimHand.mel                          ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimHaunch.mel                        ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimHead.mel                          ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimIKFKSpine.mel                     ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimIKSpine.mel                       ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimLeg.mel                           ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimMoveableEyes.mel                  ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimReverseSpine.mel                  ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildPrimRootSpine.mel                     ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildRoot.mel                              ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildSplineIK.mel                          ..\scriptPackages\scripts\CST\
copy CST\zooCSTBuildWorld.mel                             ..\scriptPackages\scripts\CST\
copy CST\zooCSTCtrlType.mel                               ..\scriptPackages\scripts\CST\
copy CST\zooCSTDependencies.mel                           ..\scriptPackages\scripts\CST\
copy CST\zooCSTHelp_flags.zooHelp                         ..\scriptPackages\scripts\CST\
copy CST\zooCSTHelp_intro.zooHelp                         ..\scriptPackages\scripts\CST\
copy CST\zooCSTHelp_tech.zooHelp                          ..\scriptPackages\scripts\CST\
copy CST\zooCSTHelp_works.zooHelp                         ..\scriptPackages\scripts\CST\
copy CST\zooCSTInfo.mel                                   ..\scriptPackages\scripts\CST\
copy CST\zooCSTMakeStretchy.mel                           ..\scriptPackages\scripts\CST\
copy CST\zooCSTMakeStretchy_limitsMethod.mel              ..\scriptPackages\scripts\CST\
copy CST\zooCSTPrimitives.mel                             ..\scriptPackages\scripts\CST\
copy CST\zooCSTTips.txt                                   ..\scriptPackages\scripts\CST\
copy CST\zooCSTUtils.mel                                  ..\scriptPackages\scripts\CST\
copy CST\zooCSTValidateFlags.mel                          ..\scriptPackages\scripts\CST\
copy CST\zooCSTWin.mel                                    ..\scriptPackages\scripts\CST\
copy CST\zooEyeSwapper.mel                                ..\scriptPackages\scripts\CST\
copy zz_scripts\zzCopyKeys.mel                            ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzExportAnimation.mel                     ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzHotkeySwap.mel                          ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzMakeUVDistortion.mel                    ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzMoveOptions.mel                         ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzPlayblaster.mel                         ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzReduceKeys.mel                          ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzRenderMaker.mel                         ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzRenderViewMenuBuild.mel                 ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzRotateOptions.mel                       ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzScaleOptions.mel                        ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzSelectorMenu.mel                        ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzToggleIsolated.mel                      ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzUVTools.mel                             ..\scriptPackages\scripts\zz_scripts\
copy zz_scripts\zzWeightTools.mel                         ..\scriptPackages\scripts\zz_scripts\

7z a -r ..\scriptPackages\zooToolBox.7z ..\scriptPackages\
pause